---
language: java
jdk: openjdk11
dist: xenial

git:
  depth: false
  quiet: true

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - master
    - release
    - /^GOOGLEDOCS-.*$/

stages:
  - build
  - release

jobs:
  include:
    - name: "Build + Tests (Community)"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/build_community.sh

    - name: "Build + Tests (Enterprise)"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/build_enterprise.sh

    - name: "WhiteSource"
      stage: build
      before_install: bash _ci/init.sh
      script: bash _ci/whitesource.sh

    - name: "Release"
      stage: release
      if: branch = release
      before_install: bash _ci/init.sh
      script: bash _ci/release_community.sh

    - name: "Release"
      stage: release
      if: branch = release
      before_install: bash _ci/init.sh
      script: bash _ci/release_enterprise.sh