---
language: java
jdk: openjdk11
dist: xenial

git:
  depth: false
  quiet: true

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2/repository

branches:
  only:
    - /.+$/

stages:
  - release

jobs:
  include:
    - name: "Test"
      stage: release
      script: bash env
   
