---
version: "2"

services:
  alfresco:
    image: alfresco/alfresco-content-repository-gd:latest
    environment:
      JAVA_OPTS: "
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=alfresco
        -Ddb.password=alfresco
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=127.0.0.1
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
        -Ddeployment.method=DOCKER_COMPOSE

        -Dtransform.service.enabled=true
        -Dtransform.service.url=http://transform-router:8095
        -Dsfs.url=http://shared-file-store:8099/

        -Dlocal.transform.service.enabled=true
        -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
        -DlocalTransform.imagemagick.url=http://imagemagick:8090/
        -DlocalTransform.libreoffice.url=http://libreoffice:8090/
        -DlocalTransform.tika.url=http://tika:8090/
        -DlocalTransform.misc.url=http://misc:8090/

        -Dlegacy.transform.service.enabled=true
        -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
        -Djodconverter.url=http://libreoffice:8090/
        -Dimg.url=http://imagemagick:8090/
        -Dtika.url=http://tika:8090/
        -Dtransform.misc.url=http://misc:8090/

        -Dcsrf.filter.enabled=false
        -Xms1500m -Xmx1500m
          "
    ports:
      - 5006:5006
    volumes:
      - alfresco-volume:/usr/local/tomcat/alf_data

  share:
    image: alfresco/alfresco-share-gd:latest
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: "
        -Xms500m
        -Xmx500m
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
        "

  transform-router:
    image: quay.io/alfresco/alfresco-transform-router:1.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
      ACTIVEMQ_URL: "nio://activemq:61616"
      IMAGEMAGICK_URL: "http://imagemagick:8090"
      PDF_RENDERER_URL: "http://alfresco-pdf-renderer:8090"
      LIBREOFFICE_URL: "http://libreoffice:8090"
      TIKA_URL: "http://tika:8090"
      MISC_URL: "http://misc:8090"
    links:
      - activemq

  alfresco-pdf-renderer:
    image: quay.io/alfresco/alfresco-pdf-renderer:2.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8090:8090
    links:
      - activemq

  imagemagick:
    image: quay.io/alfresco/alfresco-imagemagick:2.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8091:8090
    links:
      - activemq

  libreoffice:
    image: quay.io/alfresco/alfresco-libreoffice:2.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8092:8090
    links:
      - activemq

  tika:
    image: quay.io/alfresco/alfresco-tika:2.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8093:8090
    links:
      - activemq

  misc:
    image: quay.io/alfresco/alfresco-transform-misc:2.1.0
    environment:
      JAVA_OPTS: " -Xms256m -Xmx768m"
      ACTIVEMQ_URL: "nio://activemq:61616"
      FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
    ports:
      - 8096:8090
    links:
      - activemq

  shared-file-store:
    image: alfresco/alfresco-shared-file-store:0.5.3
    environment:
      JAVA_OPTS: " -Xms256m -Xmx512m"
      scheduler.content.age.millis: 86400000
      scheduler.cleanup.interval: 86400000
    ports:
      - 8099:8099
    volumes:
      - shared-file-store-volume:/tmp/Alfresco/sfs

  postgres:
    image: postgres:11.4
    environment:
      POSTGRES_PASSWORD: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_DB: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - 5432:5432
    volumes:
      - db-volume:/var/lib/postgresql/data

  solr6:
    image: alfresco/alfresco-search-services:1.3.0.1
    environment:
      # Solr needs to know how to register itself with Alfresco
      SOLR_ALFRESCO_HOST: alfresco
      SOLR_ALFRESCO_PORT: 8080
      # Alfresco needs to know how to call solr
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: 8983
      # Create the default alfresco and archive cores
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      SOLR_JAVA_MEM: "-Xms2g -Xmx2g"
    ports:
      - 8083:8983  # Browser port
    volumes:
      - solr-volume:/opt/alfresco-search-services/contentstore
      - solr-volume:/opt/alfresco-search-services/data

  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    ports:
      - 8161:8161    # Web Console
      - 5672:5672    # AMQP
      - 61616:61616  # OpenWire
      - 61613:61613  # STOMP

  digital-workspace:
    image: quay.io/alfresco/alfresco-digital-workspace:1.2.0

  proxy:
    image: quay.io/alfresco/alfresco-acs-nginx:3.0.0
    depends_on:
      - alfresco
      - digital-workspace
    ports:
      - 8080:8080
    links:
      - digital-workspace
      - alfresco
      - share

volumes:
  alfresco-volume:
    external: false
  db-volume:
    external: false
  solr-volume:
    external: false
  shared-file-store-volume:
    driver_opts:
      type: tmpfs
      device: tmpfs
