name: "Load Dependency Graph"

on:
  push:
    branches:
      - "master"
      - 'SP/**'
      - 'HF/**'
  schedule:
    - cron: '0 6 * * *'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scan-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: Alfresco/alfresco-build-tools/.github/actions/maven-dependency-scan@21bf54d131a99eaea590867434e6eccdd8654569 # v18.25.0
        with:
          java-version: '21'
          maven-version: '3.9.9'
          maven-args: -Dscopes=compile,runtime
          maven-username: ${{ secrets.NEXUS_USERNAME }}
          maven-password: ${{ secrets.NEXUS_PASSWORD }}
          maven-settings-path: "_ci/settings.xml"
