# Test image for the self-contained ("+bundled") Google Drive AMP: installs onto ACS versions that do
# not provide the Drive SDK. Uninstalls any legacy integration first, then installs with -force.

ARG ACS_VERSION=26.2.1
FROM quay.io/alfresco/alfresco-content-repository:${ACS_VERSION}

ARG IMAGEUSERNAME=alfresco
ARG TOMCAT_DIR=/usr/local/tomcat

USER root

RUN rm -f $TOMCAT_DIR/amps/alfresco-google*-repo*.amp
RUN java -jar $TOMCAT_DIR/alfresco-mmt/alfresco-mmt-*.jar uninstall \
              org.alfresco.integrations.google.docs \
              $TOMCAT_DIR/webapps/alfresco/

COPY maven/target/*+bundled.amp $TOMCAT_DIR/amps/
RUN java -jar $TOMCAT_DIR/alfresco-mmt/alfresco-mmt*.jar install \
             $TOMCAT_DIR/amps/alfresco-google*-repo*+bundled.amp $TOMCAT_DIR/webapps/alfresco -nobackup -force

USER ${IMAGEUSERNAME}
